### ISSUE TITLE
Images are difficult to find given a GitHub link

### ISSUE THREAD

**Issue by meslater1030** [allenai/beaker-image-build#1]
One of our interns recently wanted to find an image that was built based on a link she had to the successful action in GitHub. She was unable to do this. I was able to find it for her but it would have been lost if the image had been renamed since built. 

I think we could do a couple of things to address this:

* Log the image_id in the build output in the action. Or maybe the full URL. Maybe there's another way a GitHub action could surface this data, I'm not sure.
* Enable search by description for images. We do for other entities and at the very least we could tell users to search by the URL of the commit in their repo. I think this is a less good solution than above.
* Others?

**Comment by ckarenz** [comment]
We'll think about this for a week, close it out if no objections.
